-- =========================================================
-- Inventário dos salões de festas
-- Importado a partir dos checklists de conferência:
-- Salão Gourmet, Wine Bar, Pub Jogos, Barbecue A, Barbecue B,
-- Salão de Festas Kids.
--
-- Popula o módulo próprio "Inventário Salões" (tabela
-- public.salao_itens), separado do Estoque.
--
-- Pré-requisito: rodar a migration
-- supabase/migrations/20260715400000_inventario_saloes.sql antes.
--
-- Execute uma única vez (Supabase → SQL Editor → New query).
-- =========================================================

insert into public.salao_itens (nome, categoria, salao, quantidade, valor_unitario) values
  -- Salão Gourmet
  ('Pratos Rasos de Porcelana', 'Louça de Porcelana', 'Salão Gourmet', 24, 19.50),
  ('Pratos Fundos de Porcelana', 'Louça de Porcelana', 'Salão Gourmet', 24, 19.50),
  ('Pratos de Sobremesa de Porcelana', 'Louça de Porcelana', 'Salão Gourmet', 24, 14.50),
  ('Xícaras de Chá com Pires de Porcelana', 'Louça de Porcelana', 'Salão Gourmet', 24, 28.50),
  ('Facas de Aço Inox', 'Talheres', 'Salão Gourmet', 24, 10.40),
  ('Colheres de Aço Inox', 'Talheres', 'Salão Gourmet', 24, 4.00),
  ('Garfos de Aço Inox', 'Talheres', 'Salão Gourmet', 24, 5.25),
  ('Facas de Sobremesa de Aço Inox', 'Talheres', 'Salão Gourmet', 24, 4.00),
  ('Garfos de Sobremesa de Aço Inox', 'Talheres', 'Salão Gourmet', 23, 2.90),
  ('Colheres de Chá de Aço Inox', 'Talheres', 'Salão Gourmet', 24, 3.60),
  ('Taças de Vinho', 'Copos e Taças', 'Salão Gourmet', 24, 11.99),
  ('Taças de Espumante', 'Copos e Taças', 'Salão Gourmet', 24, 11.99),
  ('Taças de Cerveja', 'Copos e Taças', 'Salão Gourmet', 24, 8.99),
  ('Copos Long Drink de Vidro', 'Copos e Taças', 'Salão Gourmet', 24, 5.99),
  ('Copos de Whiskey de Vidro', 'Copos e Taças', 'Salão Gourmet', 9, 8.99),
  ('Taças de Sobremesa de Vidro', 'Copos e Taças', 'Salão Gourmet', 23, 2.60),
  ('Jarra de Vidro', 'Copos e Taças', 'Salão Gourmet', 1, 14.99),
  ('Assadeira Porcelana Média', 'Louça de Porcelana', 'Salão Gourmet', 0, 0),
  ('Assadeira Porcelana Grande', 'Louça de Porcelana', 'Salão Gourmet', 1, 0),
  ('Travessas de Aço Inox', 'Utensílios de Cozinha', 'Salão Gourmet', 2, 17.99),
  ('Jogo de Panelas 5 Peças Inox', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 499.90),
  ('Caçarola Inox', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 216.99),
  ('Chaleira Elétrica', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 59.99),
  ('Frigideira Antiaderente', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 159.99),
  ('Colheres de Arroz', 'Utensílios de Cozinha', 'Salão Gourmet', 2, 9.99),
  ('Concha', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 12.00),
  ('Escumadeira', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 11.99),
  ('Pegador de Salada', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 7.00),
  ('Pegador Multiuso', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 6.39),
  ('Colher de Sorvete', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 17.99),
  ('Cortador de Pizza Inox', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 0),
  ('Saca-rolhas/Abridor de Garrafa', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 11.99),
  ('Abridor de Latas', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 6.00),
  ('Conjunto de Facas 7 Peças', 'Talheres', 'Salão Gourmet', 1, 49.99),
  ('Coqueteleira de Aço Inox', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 28.99),
  ('Balde de Gelo', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 62.99),
  ('Bowl de Aço Inox 24cm', 'Utensílios de Cozinha', 'Salão Gourmet', 2, 15.99),
  ('Bowl de Aço Inox 30cm', 'Utensílios de Cozinha', 'Salão Gourmet', 2, 39.99),
  ('Escorredor de Massa Inox', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 59.99),
  ('Espetos Duplos', 'Churrasco', 'Salão Gourmet', 2, 15.00),
  ('Espetos Simples', 'Churrasco', 'Salão Gourmet', 2, 10.00),
  ('Grelha Argentina', 'Churrasco', 'Salão Gourmet', 1, 120.00),
  ('Tábua de Madeira', 'Churrasco', 'Salão Gourmet', 1, 179.99),
  ('Petisqueira', 'Churrasco', 'Salão Gourmet', 1, 25.00),
  ('Kit Churrasco 3 Peças', 'Churrasco', 'Salão Gourmet', 1, 79.99),
  ('Ralador de Aço Inox 4 Faces', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 14.99),
  ('Formas de Pizza', 'Utensílios de Cozinha', 'Salão Gourmet', 3, 0),
  ('Espremedor de Limão', 'Utensílios de Cozinha', 'Salão Gourmet', 1, 9.99),

  -- Wine Bar
  ('Bandeja c/ Decanter e 2 Taças de Vinho', 'Kits e Bandejas', 'Wine Bar', 1, 0),
  ('Pratos Rasos de Porcelana', 'Louça de Porcelana', 'Wine Bar', 21, 19.50),
  ('Pratos Fundos de Porcelana', 'Louça de Porcelana', 'Wine Bar', 21, 19.50),
  ('Pratos de Sobremesa de Porcelana', 'Louça de Porcelana', 'Wine Bar', 21, 14.50),
  ('Xícaras de Chá com Pires de Porcelana', 'Louça de Porcelana', 'Wine Bar', 21, 28.50),
  ('Facas de Aço Inox', 'Talheres', 'Wine Bar', 21, 10.40),
  ('Colheres de Aço Inox', 'Talheres', 'Wine Bar', 21, 4.00),
  ('Garfos de Aço Inox', 'Talheres', 'Wine Bar', 21, 5.25),
  ('Facas de Sobremesa de Aço Inox', 'Talheres', 'Wine Bar', 21, 4.00),
  ('Garfos de Sobremesa de Aço Inox', 'Talheres', 'Wine Bar', 21, 2.90),
  ('Colheres de Chá de Aço Inox', 'Talheres', 'Wine Bar', 21, 3.60),
  ('Taças de Vinho', 'Copos e Taças', 'Wine Bar', 21, 11.99),
  ('Taças de Espumante', 'Copos e Taças', 'Wine Bar', 21, 11.99),
  ('Taças de Cerveja', 'Copos e Taças', 'Wine Bar', 21, 8.99),
  ('Copos Long Drink de Vidro', 'Copos e Taças', 'Wine Bar', 21, 5.99),
  ('Copos de Whiskey de Vidro', 'Copos e Taças', 'Wine Bar', 13, 8.99),
  ('Taças de Sobremesa de Vidro', 'Copos e Taças', 'Wine Bar', 21, 2.60),
  ('Travessas de Aço Inox', 'Utensílios de Cozinha', 'Wine Bar', 4, 17.99),
  ('Chaleira Elétrica', 'Utensílios de Cozinha', 'Wine Bar', 1, 59.99),
  ('Colheres de Arroz', 'Utensílios de Cozinha', 'Wine Bar', 2, 9.99),
  ('Pegador de Salada', 'Utensílios de Cozinha', 'Wine Bar', 1, 7.00),
  ('Pá de Bolo de Aço Inox', 'Utensílios de Cozinha', 'Wine Bar', 1, 6.99),
  ('Pegador Multiuso', 'Utensílios de Cozinha', 'Wine Bar', 1, 6.39),
  ('Colher de Sorvete', 'Utensílios de Cozinha', 'Wine Bar', 1, 17.99),
  ('Saca-rolhas/Abridor de Garrafa', 'Utensílios de Cozinha', 'Wine Bar', 1, 11.99),
  ('Abridor de Latas', 'Utensílios de Cozinha', 'Wine Bar', 1, 6.00),
  ('Conjunto de Facas 7 Peças', 'Talheres', 'Wine Bar', 1, 49.99),
  ('Coqueteleira de Aço Inox', 'Utensílios de Cozinha', 'Wine Bar', 1, 28.99),
  ('Balde de Gelo', 'Utensílios de Cozinha', 'Wine Bar', 1, 62.99),
  ('Bowl de Aço Inox 24cm', 'Utensílios de Cozinha', 'Wine Bar', 2, 15.99),
  ('Bowl de Aço Inox 30cm', 'Utensílios de Cozinha', 'Wine Bar', 2, 39.99),
  ('Espetos Duplos', 'Churrasco', 'Wine Bar', 2, 15.00),
  ('Espetos Simples', 'Churrasco', 'Wine Bar', 2, 10.00),
  ('Grelha Argentina', 'Churrasco', 'Wine Bar', 1, 120.00),
  ('Tábua de Madeira', 'Churrasco', 'Wine Bar', 1, 179.99),
  ('Petisqueira', 'Churrasco', 'Wine Bar', 1, 25.00),
  ('Kit Churrasco 3 Peças', 'Churrasco', 'Wine Bar', 1, 79.99),
  ('Ralador de Aço Inox 4 Faces', 'Utensílios de Cozinha', 'Wine Bar', 1, 14.99),
  ('Espremedor de Limão', 'Utensílios de Cozinha', 'Wine Bar', 1, 9.99),

  -- Pub Jogos
  ('Bandeja c/ Garrafa, Coqueteleira, Balde de Gelo e Pegador de Gelo', 'Kits e Bandejas', 'Pub Jogos', 1, 0),
  ('Taças de Vinho', 'Copos e Taças', 'Pub Jogos', 15, 11.99),
  ('Taças de Espumante', 'Copos e Taças', 'Pub Jogos', 15, 11.99),
  ('Taças de Cerveja', 'Copos e Taças', 'Pub Jogos', 15, 8.99),
  ('Copos Refri/Suco/Cerveja de Vidro', 'Copos e Taças', 'Pub Jogos', 15, 0),
  ('Copos de Whiskey de Vidro', 'Copos e Taças', 'Pub Jogos', 12, 8.99),
  ('Saca-rolhas/Abridor de Garrafa', 'Utensílios de Cozinha', 'Pub Jogos', 1, 11.99),
  ('Coqueteleira de Aço Inox', 'Utensílios de Cozinha', 'Pub Jogos', 0, 28.99),
  ('Balde de Gelo', 'Utensílios de Cozinha', 'Pub Jogos', 1, 62.99),
  ('Conjunto de Bolas de Snooker', 'Jogos e Lazer', 'Pub Jogos', 1, 0),
  ('Raquetes de Ping Pong', 'Jogos e Lazer', 'Pub Jogos', 2, 0),
  ('Tacos de Snooker', 'Jogos e Lazer', 'Pub Jogos', 4, 0),
  ('Maleta com Bolas de Snooker', 'Jogos e Lazer', 'Pub Jogos', 1, 0),
  ('Maleta com Fichas de Poker', 'Jogos e Lazer', 'Pub Jogos', 1, 0),

  -- Barbecue A
  ('Pratos Rasos de Porcelana', 'Louça de Porcelana', 'Barbecue A', 20, 19.50),
  ('Pratos de Sobremesa de Porcelana', 'Louça de Porcelana', 'Barbecue A', 20, 14.50),
  ('Facas de Aço Inox', 'Talheres', 'Barbecue A', 20, 10.40),
  ('Colheres de Aço Inox', 'Talheres', 'Barbecue A', 20, 4.00),
  ('Garfos de Aço Inox', 'Talheres', 'Barbecue A', 20, 5.25),
  ('Taças de Cerveja', 'Copos e Taças', 'Barbecue A', 8, 8.99),
  ('Copos Long Drink de Vidro', 'Copos e Taças', 'Barbecue A', 8, 5.99),
  ('Travessas de Aço Inox', 'Utensílios de Cozinha', 'Barbecue A', 1, 17.99),
  ('Pegador de Salada', 'Utensílios de Cozinha', 'Barbecue A', 1, 7.00),
  ('Abridor de Latas', 'Utensílios de Cozinha', 'Barbecue A', 1, 6.00),
  ('Conjunto de Facas 7 Peças', 'Talheres', 'Barbecue A', 1, 49.99),
  ('Bowl de Aço Inox 24cm', 'Utensílios de Cozinha', 'Barbecue A', 2, 15.99),
  ('Espetos Duplos', 'Churrasco', 'Barbecue A', 1, 15.00),
  ('Espetos Simples', 'Churrasco', 'Barbecue A', 1, 10.00),
  ('Grelha Argentina', 'Churrasco', 'Barbecue A', 1, 120.00),
  ('Tábua de Madeira', 'Churrasco', 'Barbecue A', 1, 179.99),
  ('Petisqueira', 'Churrasco', 'Barbecue A', 1, 25.00),
  ('Kit Churrasco 3 Peças', 'Churrasco', 'Barbecue A', 1, 79.99),
  ('Espremedor de Limão', 'Utensílios de Cozinha', 'Barbecue A', 1, 9.99),
  ('Suporte para Papel Toalha', 'Utensílios de Cozinha', 'Barbecue A', 1, 0),

  -- Barbecue B
  ('Pratos Rasos de Porcelana', 'Louça de Porcelana', 'Barbecue B', 20, 19.50),
  ('Pratos de Sobremesa de Porcelana', 'Louça de Porcelana', 'Barbecue B', 20, 14.50),
  ('Facas de Aço Inox', 'Talheres', 'Barbecue B', 20, 10.40),
  ('Colheres de Aço Inox', 'Talheres', 'Barbecue B', 20, 4.00),
  ('Garfos de Aço Inox', 'Talheres', 'Barbecue B', 20, 5.25),
  ('Taças de Cerveja', 'Copos e Taças', 'Barbecue B', 8, 8.99),
  ('Copos Long Drink de Vidro', 'Copos e Taças', 'Barbecue B', 8, 5.99),
  ('Travessas de Aço Inox', 'Utensílios de Cozinha', 'Barbecue B', 1, 17.99),
  ('Pegador de Salada', 'Utensílios de Cozinha', 'Barbecue B', 1, 7.00),
  ('Abridor de Latas', 'Utensílios de Cozinha', 'Barbecue B', 1, 6.00),
  ('Conjunto de Facas 7 Peças', 'Talheres', 'Barbecue B', 1, 49.99),
  ('Bowl de Aço Inox 24cm', 'Utensílios de Cozinha', 'Barbecue B', 2, 15.99),
  ('Espetos Duplos', 'Churrasco', 'Barbecue B', 1, 15.00),
  ('Espetos Simples', 'Churrasco', 'Barbecue B', 1, 10.00),
  ('Grelha Argentina', 'Churrasco', 'Barbecue B', 1, 120.00),
  ('Tábua de Madeira', 'Churrasco', 'Barbecue B', 1, 179.99),
  ('Petisqueira', 'Churrasco', 'Barbecue B', 1, 25.00),
  ('Kit Churrasco 3 Peças', 'Churrasco', 'Barbecue B', 1, 79.99),
  ('Espremedor de Limão', 'Utensílios de Cozinha', 'Barbecue B', 1, 9.99),
  ('Suporte para Papel Toalha', 'Utensílios de Cozinha', 'Barbecue B', 1, 0),

  -- Salão de Festas Kids
  ('Pratos Rasos de Porcelana', 'Louça de Porcelana', 'Salão de Festas Kids', 36, 19.50),
  ('Pratos Fundos de Porcelana', 'Louça de Porcelana', 'Salão de Festas Kids', 20, 19.50),
  ('Pratos de Sobremesa de Porcelana', 'Louça de Porcelana', 'Salão de Festas Kids', 40, 14.50),
  ('Xícaras de Chá com Pires de Porcelana', 'Louça de Porcelana', 'Salão de Festas Kids', 40, 28.50),
  ('Facas de Aço Inox', 'Talheres', 'Salão de Festas Kids', 40, 10.40),
  ('Colheres de Aço Inox', 'Talheres', 'Salão de Festas Kids', 40, 4.00),
  ('Garfos de Aço Inox', 'Talheres', 'Salão de Festas Kids', 40, 5.25),
  ('Facas de Sobremesa de Aço Inox', 'Talheres', 'Salão de Festas Kids', 40, 4.00),
  ('Garfos de Sobremesa de Aço Inox', 'Talheres', 'Salão de Festas Kids', 37, 2.90),
  ('Colheres de Chá de Aço Inox', 'Talheres', 'Salão de Festas Kids', 40, 3.60),
  ('Taças de Vinho', 'Copos e Taças', 'Salão de Festas Kids', 36, 11.99),
  ('Taças de Espumante', 'Copos e Taças', 'Salão de Festas Kids', 40, 11.99),
  ('Taças de Cerveja', 'Copos e Taças', 'Salão de Festas Kids', 40, 8.99),
  ('Copos Long Drink de Vidro', 'Copos e Taças', 'Salão de Festas Kids', 40, 5.99),
  ('Copos de Whiskey de Vidro', 'Copos e Taças', 'Salão de Festas Kids', 24, 8.99),
  ('Taças de Sobremesa de Vidro', 'Copos e Taças', 'Salão de Festas Kids', 40, 2.60),
  ('Jarra de Vidro', 'Copos e Taças', 'Salão de Festas Kids', 1, 14.99),
  ('Assadeira Porcelana Média', 'Louça de Porcelana', 'Salão de Festas Kids', 1, 53.99),
  ('Assadeira Porcelana Grande', 'Louça de Porcelana', 'Salão de Festas Kids', 1, 90.99),
  ('Travessas de Aço Inox', 'Utensílios de Cozinha', 'Salão de Festas Kids', 4, 17.99),
  ('Jogo de Panelas 5 Peças Inox', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 499.90),
  ('Caçarola Inox', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 216.99),
  ('Chaleira Elétrica', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 59.99),
  ('Frigideira Antiaderente', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 159.99),
  ('Colheres de Arroz', 'Utensílios de Cozinha', 'Salão de Festas Kids', 4, 9.99),
  ('Concha', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 12.00),
  ('Escumadeira', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 11.99),
  ('Pegador de Salada', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 7.00),
  ('Pá de Bolo de Aço Inox', 'Utensílios de Cozinha', 'Salão de Festas Kids', 0, 6.99),
  ('Pegador Multiuso', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 6.39),
  ('Colher de Sorvete', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 17.99),
  ('Saca-rolhas/Abridor de Garrafa', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 11.99),
  ('Abridor de Latas', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 6.00),
  ('Conjunto de Facas 7 Peças', 'Talheres', 'Salão de Festas Kids', 1, 49.99),
  ('Coqueteleira de Aço Inox', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 28.99),
  ('Balde de Gelo', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 62.99),
  ('Bowl de Aço Inox 24cm', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 15.99),
  ('Bowl de Aço Inox 30cm', 'Utensílios de Cozinha', 'Salão de Festas Kids', 3, 39.99),
  ('Escorredor de Massa Inox', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 59.99),
  ('Espetos Duplos', 'Churrasco', 'Salão de Festas Kids', 2, 15.00),
  ('Espetos Simples', 'Churrasco', 'Salão de Festas Kids', 2, 10.00),
  ('Grelha Argentina', 'Churrasco', 'Salão de Festas Kids', 1, 120.00),
  ('Tábua de Madeira', 'Churrasco', 'Salão de Festas Kids', 1, 179.99),
  ('Petisqueira', 'Churrasco', 'Salão de Festas Kids', 1, 25.00),
  ('Kit Churrasco 3 Peças', 'Churrasco', 'Salão de Festas Kids', 1, 79.99),
  ('Ralador de Aço Inox 4 Faces', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 14.99),
  ('Espremedor de Limão', 'Utensílios de Cozinha', 'Salão de Festas Kids', 1, 9.99);
